#!/usr/bin/env bash
# © Copyright IBM Corporation 2015.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html

set -e

stop() {
	echo "----------------------------------------"
	echo "Stopping node $NODE_NAME..."
	mqsistop $NODE_NAME
}

startIIB() {

	echo "----------------------------------------"
	$IIB_BIN_PATH version
	echo "----------------------------------------"

	local NODE_EXISTS=$(
		mqsilist | grep $NODE_NAME >/dev/null
		echo $?
	)

	if [ ${NODE_EXISTS} -ne 0 ]; then

		echo "----------------------------------------"
		echo "Start rsyslogd"
		sudo /usr/sbin/rsyslogd
		echo "----------------------------------------"
		echo "Node $NODE_NAME does not exist..."
		echo "Creating node $NODE_NAME"
		mqsicreatebroker $NODE_NAME
		echo "----------------------------------------"
		echo "Starting node $NODE_NAME"
		mqsistart $NODE_NAME
		echo "----------------------------------------"
		echo "Creating integration server $SERVER_NAME"
		mqsicreateexecutiongroup $NODE_NAME -e $SERVER_NAME -w 120
		echo "----------------------------------------"
		shopt -s nullglob
		for f in /tmp/BARs/*; do
			echo "Deploying $f ..."
			mqsideploy $NODE_NAME -e $SERVER_NAME -a $f -w 120
		done
		echo "----------------------------------------"
	else
		echo "----------------------------------------"
		echo "Starting node $NODE_NAME"
		mqsistart $NODE_NAME
		echo "----------------------------------------"
	fi

}

monitor() {
	echo "----------------------------------------"
	echo "Running - stop container to exit"
	while true; do sleep 1; done
}

if [[ -z "$@" ]]; then
	startIIB
else
	$IIB_BIN_PATH $@
fi

trap stop SIGTERM SIGINT
monitor
